#!/usr/bin/env python3
"""Developer-only Unicode 15 names for native Python regular expressions.

Requires Python 3.12's Unicode 15 database. Product binaries embed the generated
data; they never execute Python or download Unicode resources.
"""
import hashlib
import json
from pathlib import Path
import struct
import unicodedata
import urllib.request

ROOT = Path(__file__).resolve().parents[1]
VERSION = "15.0.0"
URL = "https://raw.githubusercontent.com/unicode-org/unicodetools/main/unicodetools/data/ucd/15.0.0/NameAliases.txt"
SHA256 = "3e39509e8fae3e5d50ba73759d0b97194501d14a9c63107a6372a46b38be18e8"
PREFIXES = [
    "CJK UNIFIED IDEOGRAPH-", "CJK COMPATIBILITY IDEOGRAPH-",
    "TANGUT IDEOGRAPH-", "NUSHU CHARACTER-", "KHITAN SMALL SCRIPT CHARACTER-",
]


def main():
    if unicodedata.unidata_version != VERSION:
        raise RuntimeError(f"Expected Unicode {VERSION}, got {unicodedata.unidata_version}")
    aliases = urllib.request.urlopen(URL).read()
    if hashlib.sha256(aliases).hexdigest() != SHA256:
        raise RuntimeError("Unicode name aliases checksum differs from pinned input")
    names = {}
    algorithmic = {prefix: [] for prefix in PREFIXES}
    for code in range(0x110000):
        name = unicodedata.name(chr(code), None)
        if name is None:
            continue
        for prefix in PREFIXES:
            if name == f"{prefix}{code:X}":
                algorithmic[prefix].append(code)
                break
        else:
            names[name] = code
    for line in aliases.decode().splitlines():
        line = line.split("#", 1)[0].strip()
        if line:
            code, name, _kind = line.split(";")
            names[name] = int(code, 16)
    entries = bytearray()
    offsets = []
    for name, code in sorted(names.items()):
        offsets.append(len(entries))
        entries += struct.pack("<I", code) + name.encode("ascii") + b"\0"
    data = struct.pack("<I", len(offsets)) + b"".join(struct.pack("<I", offset) for offset in offsets) + entries
    destination = ROOT / "vendor/unicode"
    (destination / "names.bin").write_bytes(data)
    (destination / "names.zig").write_text('//! Generated by scripts/generate_unicode_names.py; Unicode 15.0.0.\npub const data = @embedFile("names.bin");\n')
    ranges = []
    for prefix, codes in algorithmic.items():
        if not codes:
            continue
        begin = end = codes[0]
        for code in codes[1:]:
            if code == end + 1:
                end = code
            else:
                ranges.append((prefix, begin, end))
                begin = end = code
        ranges.append((prefix, begin, end))
    text = '// Generated Unicode 15.0.0 algorithmic names; see vendor/unicode/LICENSE.\n'
    text += 'pub const ranges = [_]struct { prefix: []const u8, first: u21, last: u21 }{\n'
    text += ''.join(f'    .{{ .prefix = "{prefix}", .first = 0x{begin:x}, .last = 0x{end:x} }},\n' for prefix, begin, end in ranges)
    text += '};\n'
    (ROOT / "src/project/unicode_name_ranges.zig").write_text(text)
    provenance = {"unicode": VERSION, "generator": "scripts/generate_unicode_names.py", "aliases": {"url": URL, "sha256": SHA256}, "names_sha256": hashlib.sha256(data).hexdigest(), "entries": len(names)}
    (destination / "names-source.json").write_text(json.dumps(provenance, indent=2) + "\n")
    print(f"Generated {len(names)} named characters/aliases and {len(ranges)} algorithmic ranges ({len(data)} bytes)")


if __name__ == "__main__":
    main()
